version: '3.3'
services:
  freepbx:
    build: .
    image: crazyquark/freepbx:14-armhf
    container_name: freepbx
    volumes:
      - freepbx_backup:/backup
      - freepbx_recordings:/var/spool/asterisk/monitor
      - freepbx_db:/var/lib/mysql
    environment:
      - RTP_START=18000
      - RTP_FINISH=18100
    ports:
      - 9090:80 
      - 3306:3306
      - 5060:5060/udp
      - 5061:5061/udp
      - 5160:5160
      - 5161:5161
      - 4569:4569
      - 18000-18100:18000-18100/udp
#    devices:
#      - /dev/ttyUSB0:/dev/ttyUSB0
#      - /dev/ttyUSB1:/dev/ttyUSB1
#      - /dev/ttyUSB2:/dev/ttyUSB2

volumes:
  freepbx_db:
  freepbx_recordings:
  freepbx_backup:
